# # Use Python 3.9 as the base image
# FROM python:3.9-slim

# # Create a non-root user
# RUN useradd -m -u 1000 user
# USER user

# # Set environment variables
# ENV PATH="/home/user/.local/bin:$PATH"

# # Set the working directory
# WORKDIR /app

# # Copy the requirements file from `api/` and install dependencies
# COPY --chown=user ./requirements.txt requirements.txt
# RUN pip install --no-cache-dir --upgrade -r requirement.txt

# # Copy the full project after installing dependencies
# COPY --chown=user . .

# # Expose the required port
# EXPOSE 7860
# COPY --chown=user . /app

# # Run the FastAPI app using Uvicorn
# CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]


# Read the doc: https://huggingface.co/docs/hub/spaces-sdks-docker
# you will also find guides on how best to write your Dockerfile

FROM python:3.9

RUN useradd -m -u 1000 user
USER user
ENV PATH="/home/user/.local/bin:$PATH"

WORKDIR /app

COPY --chown=user ./requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY --chown=user . /app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]
